[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sbc_citu8_cert_dapp = "uwWiGs51F6LeLHd84pLCTALydnyYJCT1kKmxmBVv7EV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/blissfuljuan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
